# Config file for Travis CI
language: node_js
node_js:
  - "node"
before_deploy: "npm run deploy"
deploy:
  provider: s3
  access_key_id: "AKIAIFR3WGPPFUC6I2OQ"
  secret_access_key: "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"
  bucket: "jonathanrys"
  local_dir: build/