# Config file for Travis CI
language: node_js
node_js:
  - "node"
before_deploy: "yarn run build"
deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: "jonathanrys"
  local_dir: build